version: '3.9'
services:
  # zookeeper:
  #   image: confluentinc/cp-zookeeper:7.5.1
  #   container_name: kafkadeb-zookeeper
  #   ports:
  #     - "2181:2181"
  #   environment:
  #     ZOOKEEPER_CLIENT_PORT: 2181
  #     ZOOKEEPER_TICK_TIME: 2000

  # kafka:
  #   image: confluentinc/cp-kafka:7.5.1
  #   container_name: kafkadeb-kafka
  #   ports:
  #     - "9092:9092"
  #   environment:
  #     KAFKA_BROKER_ID: 1
  #     KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
  #     KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
  #     KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
  #   depends_on:
  #     - zookeeper

  # bez zookiper
  # kafka:
  #   image: confluentinc/cp-kafka:latest
  #   environment:
  #     - KAFKA_KRAFT_MODE=true
  #     # Usuń lub zakomentuj poniższą linię
  #     # - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
  #     - KAFKA_ADVERTISED_LISTENER=PLAINTEXT://localhost:9092
  #     - KAFKA_LISTENER_SECURITY_PROTOCOL=PLAINTEXT
  #     - KAFKA_LISTENER_PORT=9092
  #     - KAFKA_LISTENER_NAME=PLAINTEXT
  #     - KAFKA_LISTENER_INTER_BROKER_LISTENER_NAME=PLAINTEXT
  #     - KAFKA_LOG_DIRS=/var/lib/kafka/data
  #     - KAFKA_LOG_RETENTION_HOURS=168
  #     - KAFKA_LOG_SEGMENT_BYTES=1073741824
  #   ports:
  #     - "9092:9092"
  #   volumes:
  #     - /var/lib/kafka/data

  # https://hub.docker.com/r/bashj79/kafka-kraft
  # https://github.com/bashj79/kafka-kraft-docker

  kafka:
    image: bashj79/kafka-kraft
    ports:
      - "9092:9092"

  magic:
    image: "digitsy/kafka-magic"
    ports:
      - "8080:80"

  postgres:
    image: postgres:16.2-bullseye
    container_name: kafkadeb-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: debezium_user
      POSTGRES_PASSWORD: my_password
      POSTGRES_DB: my_database
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  kafka-connect:
    image: debezium/connect:2.4
    container_name: kafkadeb-kafka-connect
    ports:
      - "8083:8083"
    environment:
      BOOTSTRAP_SERVERS: kafka:9092
      GROUP_ID: 1
      CONFIG_STORAGE_TOPIC: connect-configs
      OFFSET_STORAGE_TOPIC: connect-offsets
      STATUS_STORAGE_TOPIC: connect-status
      KEY_CONVERTER: org.apache.kafka.connect.json.JsonConverter
      VALUE_CONVERTER: org.apache.kafka.connect.json.JsonConverter
      VALUE_CONVERTER_SCHEMAS_ENABLE: false
      KEY_CONVERTER_SCHEMAS_ENABLE: false
      PLUGIN_PATH: /kafka/connect
    volumes:
      - ./plugins:/kafka/connect
    depends_on:
      - kafka
      - postgres

volumes:
  postgres_data:
